services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.docker
    depends_on:
      - redis
      - python-service
      - db

  python-service:
    build:
      context: ./python-services
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - redisdata:/var/lib/redis/data

volumes:
  pgdata:
  redisdata: